# Ansible Playbook for Subutai Postgresql Blueprint
--- 

- hosts: postgres
  remote_user: root
  tasks:

    # -------------------------------------------------------------------------
    # Freshen up the host
    # -------------------------------------------------------------------------

    - name: Disable dpkg fsync
      raw: test -e /etc/dpkg/dpkg.cfg.d/unsafe-io || echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/unsafe-io

    - name: Upgrade debian
      apt:
        update_cache: true
        upgrade: true

    # -------------------------------------------------------------------------
    # Install shit that should be there and fix locales
    # -------------------------------------------------------------------------

    - name: Install setup tools
      apt:
        name: "{{ item }}"
        allow_unauthenticated: yes
      with_items:
        - dirmngr
        - ca-certificates
        - sudo
        - locales

    - name: Transfer locales_setup.sh
      copy: src=locales_setup.sh dest=/root/locales_setup.sh

    - name: Execute locales_setup.sh
      command: bash /root/locales_setup.sh

    - name: Install required debs
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - php7.0
        - php7.0-cgi
        - php7.0-mysql
        - apache2
        - libapache2-mod-php7.0
        - unzip 
        - mariadb-server
        - python-mysqldb

    # -------------------------------------------------------------------------
    # Install NodeSource NodeJS, NPM, and Grunt
    # -------------------------------------------------------------------------

    - name: Install repository keys for NodeSource repo
      apt_key: 
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
    
    - name: Add binary repository for NodeSource repo
      apt_repository:
        repo: deb https://deb.nodesource.com/node_11.x/ xenial main
        update_cache: true
        state: present
    
    - name: Add source repository for NodeSource repo
      apt_repository:
        repo: deb-src https://deb.nodesource.com/node_11.x/ xenial main
        update_cache: true
        state: present
    
    - name: Install nodejs
      apt:
        name: nodejs
        state: present

    - name: Install grunt
      npm:
        name: grunt 
        global: yes

    # -------------------------------------------------------------------------
    # Setup PHP and Create DB User
    # -------------------------------------------------------------------------

    - name: Install limits.ini
      template: 
        src: limits.ini
        dest: /etc/php/7.0/mods-available/limits.ini

    - name: Activate limits.ini
      shell: phpenmod limits

    - name: Create database
      mysql_db:
        name: mautic
        state: present
        encoding: utf8

    - name: Create database user
      mysql_user:
        name: mautic
        password: "{{ subutai.user_variables.password }}"
        priv: "mautic.*:ALL"

