# Ansible Playbook for Subutai Postgresql Blueprint
--- 

- hosts: mautic
  remote_user: root
  tasks:

    # -------------------------------------------------------------------------
    # Freshen up the host
    # -------------------------------------------------------------------------

    - name: Disable dpkg fsync
      raw: test -e /etc/dpkg/dpkg.cfg.d/unsafe-io || echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/unsafe-io

    - name: Upgrade debian
      apt:
        update_cache: true
        upgrade: true

    # -------------------------------------------------------------------------
    # Install shit that should be there and fix locales
    # -------------------------------------------------------------------------

    - name: Install setup tools
      apt:
        name:
          - dirmngr
          - ca-certificates
          - apt-transport-https
          - sudo
          - locales
        allow_unauthenticated: yes

    - name: Transfer locales_setup.sh
      copy: src=locales_setup.sh dest=/root/locales_setup.sh

    - name: Execute locales_setup.sh
      command: bash /root/locales_setup.sh

    - name: Install required debs
      apt:
        name:
          - git
          - php7.0
          - php7.0-cgi
          - php7.0-mysql
          - php-xml
          - php-mbstring
          - php-curl
          - php-amqplib
          - php-zip
          - php-mcrypt
          - php-intl
          - php-imap
          - php-mailparse
          - composer
          - nginx
          - libapache2-mod-php7.0
          - unzip 
          - mariadb-server
          - python-mysqldb

    # -------------------------------------------------------------------------
    # Install NodeSource NodeJS, NPM, and Grunt
    # -------------------------------------------------------------------------

    - name: Install repository keys for NodeSource repo
      apt_key: 
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
    
    - name: Add binary repository for NodeSource repo
      apt_repository:
        repo: deb https://deb.nodesource.com/node_11.x/ xenial main
        update_cache: true
        state: present
    
    - name: Add source repository for NodeSource repo
      apt_repository:
        repo: deb-src https://deb.nodesource.com/node_11.x/ xenial main
        update_cache: true
        state: present
    
    - name: Install nodejs
      apt:
        name: nodejs
        state: present

    - name: Install grunt
      npm:
        name: grunt 
        global: yes

    # -------------------------------------------------------------------------
    # Setup PHP and Create DB User
    # -------------------------------------------------------------------------

    - name: Upload limits.ini
      template: 
        src: limits.ini
        dest: /etc/php/7.0/mods-available/limits.ini

    - name: Activate limits.ini
      shell: phpenmod limits

    - name: Create database
      mysql_db:
        name: mautic
        state: present
        encoding: utf8

    - name: Create database user
      mysql_user:
        name: mautic
        password: "{{ subutai.user_variables.password }}"
        priv: "mautic.*:ALL"

    # -------------------------------------------------------------------------
    # Mautic Setup
    # -------------------------------------------------------------------------
    
    - name: Clone Mautic Repository
      git:
        clone: yes
        dest: /var/www/html/mautic
        repo: https://github.com/mautic/mautic.git
        version: 2.15.0

    - name: Update PHP with Composer
      composer:
        command: install
        working_dir: /var/www/html/mautic

    - name: Chmod to www-data
      file:
        dest: /var/www
        owner: www-data
        group: www-data
        state: directory
        recurse: yes

    # Need to confirm this is actually working properly
    - name: Add block to PHP configuration files
      blockinfile:
        path:
          - /etc/php/7.0/apache2/php.ini
          - /etc/php/7.0/cli/php.ini
          - /etc/php/7.0/cgi/php.ini
        block: |
          file_uploads = On
          allow_url_fopen = On
          memory_limit = 512M
          max_execution_time = 360
          cgi.fix_pathinfo = 0
          date.timezone = Etc/UTC
        create: yes
    
    # -------------------------------------------------------------------------
    # NGINX Setup
    # -------------------------------------------------------------------------
    
    - name: Setup mautic site
      template: 
        src: mautic.conf
        dest: /etc/nginx/sites-available/mautic.conf
        force: yes

    - name: Link available site to enable
      file:
        src: /etc/nginx/sites-available/mautic.conf
        dest: /etc/nginx/sites-enabled/mautic.conf
        state: link

    - name: Restart NGINX
      systemd:
        name: nginx
        state: restarted

